# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Intro to Software Applications in Biotechnology
description:      'UMBC BTEC 330'

url:              https://rahm0054.github.io/btec330/
baseurl:          /

author:
  name:           'Nandita Rahman'
  url:            https://www.linkedin.com/in/nanditarahman/

github:
  repo:           https://github.com/rahm0054/btec330/tree/gh-pages

gems:
  - jekyll-redirect-from
